### ISSUE TITLE
What if products more than 100?

### ISSUE THREAD

**Issue by goodok21** [moltin/gatsby-source-moltin#18]
I have 5000+ products in Moltin and how can I fetch all of this to generate pages via `gatsby-node.js`?

Tried:
- allMoltinProduct(skip: 100) 
- allMoltinProduct(limit: 6000)

it's doesn't work, I always see 100 products

**Comment by ynnoj** [comment]
@goodok21 
> By default, page lengths are set to 100. You can adjust this setting globally for your project via the settings endpoint or override on any single call. There is a maximum page length of 100 for any paginated call.

There is a hard limit of `100` for any paginated call. You'll need to paginate requests accordingly using the `skip` and `limit` inputs in your query.

https://docs.moltin.com/api/basics/pagination

**Comment by ynnoj** [comment]
Closing. Please reopen if you still need guidance with this 😄

**Comment by notrab** [comment]
@goodok21 If you upgrade to the latest version you'll get more than 100 products now 😄
