### ISSUE TITLE
Currency format is wrong

### ISSUE THREAD

**Issue by shendriksza** [moltin/gatsby-source-moltin#19]
I've changed the currency format on Moltin.  The change is visible when I make curl request, but on GraphiQL the changes are not visible. I can only assume the gatsby-source-moltin library is at fault?

**Comment by ynnoj** [comment]
Have you rebuilt your store/Gatsby project since making the change at Moltin?

**Comment by shendriksza** [comment]
I did multiple times. I played around a bit now, and after changing the price on one of my items the format change kicked in on all products

**Comment by ynnoj** [comment]
You may have been hitting a cached product API response. Updating the currency should purge that cached response.

**Comment by ynnoj** [comment]
Sometimes you may also need to clear the Gatsby project `.cache` directory between builds. This is currently a known Gatsby issue.
