### ISSUE TITLE
Cannot destructure property next of 'undefined'

### ISSUE THREAD

**Issue by ehallvard** [moltin/gatsby-source-moltin#39]
If I use the latest version (1.6.0) my graphql query fails with the following errors:

`gatsby-source-moltin: ERROR TypeError: Cannot destructure property `next` of
 'undefined' or 'null'.
    at getPaginatedResource (/Users/user/dev/project/node_modules/@moltin/gatsby-source-moltin/gatsby-node.js:187:11)`

Downgrading 1.4.1 made it work.
I'm running this query:
` allProducts: allMoltinProduct {
        edges {
          node {
            id
            slug
            sku
          }
        }
      }`

**Comment by notrab** [comment]
Hi @ehallvard 

Thanks for reporting this.

Are you able to see if this is resolved if you add a collection/category?

We're in the process of fixing another issue which might also help here. I'll keep you updated on a fix.

**Comment by ehallvard** [comment]
Adding a collection and a category solved it

**Comment by notrab** [comment]
@ehallvard thanks! I'll keep you posted when we have the fix.

**Comment by samblacklock** [comment]
@ehallvard we've just merged https://github.com/moltin/gatsby-source-moltin/pull/40 which should solve your issue

**Comment by notrab** [comment]
@ehallvard it should be fixed in the latest release. Are you able to confirm?

**Comment by ehallvard** [comment]
I can confirm that it works without any collections or categories. Thanks guys!
